<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?= $title ?></title>
		<link href="<?= AgilePHP::getDocumentRoot() ?>/view/css/style.css" type="text/css" rel="stylesheet"/>
		<link href="<?= AgilePHP::getDocumentRoot() ?>/view/css/tree-icons.css" type="text/css" rel="stylesheet"/>
		<link href="<?= AgilePHP::getDocumentRoot() ?>/components/ext/resources/css/ext-all.css" type="text/css" rel="stylesheet"/>
		<link href="<?= AgilePHP::getDocumentRoot() ?>/components/ext/ux/form/fileuploadfield.css" type="text/css" rel="stylesheet"/>
		<![if IE]>
    		<link href="<?= AgilePHP::getDocumentRoot() ?>/view/css/ie.css" rel="stylesheet" type="text/css" />
	    <![endif]>
		<![if !IE]>
    		<link href="<?= AgilePHP::getDocumentRoot() ?>/view/css/ff.css" rel="stylesheet" type="text/css" />
	    <![endif]>
		<script type="text/javascript" src="<?= AgilePHP::getRequestBase() ?>/RemotingController/getBaseJS/<?= AgilePHP::isInDebugMode() ?>"></script>
		<script type="text/javascript" src="<?= AgilePHP::getRequestBase() ?>/RemotingController/index/ConfigsRemote"></script>
		<script type="text/javascript" src="<?= AgilePHP::getDocumentRoot() ?>/components/ext/adapter/ext/ext-base.js"></script>
		<script type="text/javascript" src="<?= AgilePHP::getDocumentRoot() ?>/components/ext/ext-all.js"></script>
		<script type="text/javascript" src="<?= AgilePHP::getDocumentRoot() ?>/view/js/Ext.Fx.shake.js"></script>
		<script type="text/javascript" src="<?= AgilePHP::getDocumentRoot() ?>/view/js/AgilePHP.Studio.js"></script>
		<script type="text/javascript" src="<?= AgilePHP::getDocumentRoot() ?>/view/js/AgilePHP.Studio.LoginWindow.js"></script>
		<script type="text/javascript">
			Ext.onReady( function() {

					AgilePHP.Studio.setDebug( true );
					AgilePHP.Remoting.setController( 'RemotingController' );

					Ext.QuickTips.init();

					AgilePHP.Studio.bootstrap();
					new AgilePHP.Studio.LoginWindow();
			});
		</script>
	</head>

	<body>
		
	</body>
</html>