<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?php echo $title; ?></title>
		<script src="<?php echo AgilePHP::getDocumentRoot() ?>/AgilePHP/AgilePHP.js"></script>
		<link href="<?php echo AgilePHP::getDocumentRoot() ?>/view/css/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>
		<?php require_once 'header.html'; ?>
		<?php require_once 'admin_navigation.phtml'; ?>
		<?php echo isset($content) ? $content : 'Welcome to the admin area!'; ?>
		<?php require_once 'footer.html'; ?>
	</body>
</html>