<table border="0" style="padding-bottom: 5px;">
	<tr>
		<td>
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/IndexController/admin">Home</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/UserController">Users</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/RoleController">Roles</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase() ?>/LoginController/logout">Logout</a>
		</td>
		<!-- #@AgilePHPGen -->
	</tr>
</table>