<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/xhtml; charset=utf-8"/>
		<title><?= $title; ?></title>
		<link href="<?= AgilePHP::getDocumentRoot() ?>/view/css/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>
		<?php require_once 'header.html'; ?>
		<div class="error"><?php if(isset($error)) echo $error; ?></div>
		<?php require_once 'footer.html'; ?>
	</body>
</html>