<table border="0" style="padding: 5px 5px 5px 5px;">
	<tr>
		<td>
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/IndexController/admin">Administration</a> &gt;
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getDocumentRoot(); ?>/../studio" target="_blank">Studio</a>
		</td>

		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/UserController">Users</a>
		</td>

		<!-- 
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/UserRoleController">Users/Role Relationships</a>
		</td>
		-->

		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/RoleController">Roles</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/SessionController">Sessions</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/InventoryController">Inventory</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/MailingController">Mailing</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/TestComponent">Test Component</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase(); ?>/TestPhar">Test Phar</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getRequestBase() ?>/LoginController/logout">Logout</a>
		</td>
	</tr>
</table>


<table border="0" style="padding: 5px 5px 25px 55px;">
	<tr>
	    <td>Services &gt;</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getDocumentRoot(); ?>/index.php/users" target="_blank">Users REST API</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getDocumentRoot(); ?>/index.php/SoapRpcEncodedTestAPI/wsdl" target="_blank">SOAP RPC/Encoded</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getDocumentRoot(); ?>/index.php/SoapRpcLiteralTestAPI/wsdl" target="_blank">SOAP RPC/Literal</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?php echo AgilePHP::getDocumentRoot(); ?>/index.php/SoapDocumentLiteralTestAPI/wsdl" target="_blank">SOAP Document/Literal (wrapped)</a>
		</td>
	</tr>
</table>