<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?php echo $title; ?></title>
		<script src="<?php echo AgilePHP::getFramework()->getDocumentRoot(); ?>/../src/AgilePHP.js"></script>
		<link href="<?php echo AgilePHP::getFramework()->getDocumentRoot(); ?>/view/css/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>
		<?php require_once 'header.html'; ?>

		<?php require_once 'admin_navigation.phtml'; ?>

		<?php
			  if( !isset( $content ) )
			  	  echo 'Welcome to the admin area!';
			  else
			  	  echo $content
		 ?>

		<?php require_once 'footer.html'; ?>
	</body>
</html>