<table border="0" style="padding-bottom: 5px;">
	<tr>
		<td>
			<a href="<?= AgilePHP::getRequestBase(); ?>/IndexController/admin">Admin Area</a> &gt;
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getDocumentRoot(); ?>/../studio" target="_blank">Studio</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/UserController">Users</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/RoleController">Roles</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/SessionController">Sessions</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/InventoryController">Inventory</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/MailingController">Mailing</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/TestComponent">Test Component</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase(); ?>/TestPhar">Test Phar</a>
		</td>
		<td style="padding-left: 10px;">
			<a href="<?= AgilePHP::getRequestBase() ?>/LoginController/logout">Logout</a>
		</td>
	</tr>
</table>