<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?= $title ?></title>
		<link href="<?= AgilePHP::getFramework()->getDocumentRoot() ?>/view/css/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>
		<?php require_once 'header.html'; ?>

		<div>
			<form name="frmContact" method="post" action="<?= AgilePHP::getFramework()->getRequestBase() ?>/IndexController/contactSubmit">
				<?php if( isset( $formResult ) ) echo '<div style="padding-top: 20px;">' . $formResult . '</div>'; ?>
				<table border="0" style="padding-top: 25px">
					<tr>
						<th align="center" colspan="2">Contact Us</th>
					</tr>
					<tr>
						<td>Name:</td>
						<td><input type="text" name="name"/></td>
					</tr>
					<tr>
						<td>Phone:</td>
						<td><input type="text" name="phone"/></td>
					</tr>
					<tr>
						<td>Email:</td>
						<td><input type="text" name="email"/></td>
					</tr>
					<tr>
						<td>Comments:</td>
						<td><textarea rows="5" cols="25" name="comments"></textarea></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td><input type="submit" value="Send Email"/></td>
					</tr>
				</table>
			</form>	
		</div>

		<?php require_once 'footer.html'; ?>
	</body>
</html>