<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?php echo $title; ?></title>
		<link href="/AgilePHP-dev/web/view/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>

		<?php
		
			if( isset( $error ) )
				echo '<span class="error">Error: ' . $error . '</span>';
		?>

	</body>
</html>