<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<script type="text/javascript" src="/AgilePHP/test/index.php/IndexController/getBaseJS"></script>
		<title>AgilePHP Form Example</title>
	</head>
	<body>
		<?php
			if( isset( $form ) )
				echo $form;

			if( isset( $parameters ) )
				print_r( $parameters );
		?>
	</body>
</html>