<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<script type="text/javascript" src="/AgilePHP/test/index.php/IndexController/getBaseJS"></script>
		<title>AgilePHP Form Example using #@RequestParm Interceptor</title>
		<style type="text/css">
		.label { float: left; }
		.inputField { margin-left: 100px; }
		.required { color: #FF0000; }
		</style>
	</head>

	<body>

		<div id="container">

			<form name="frmRequestParmTest" action="<?= AgilePHP::getRequestBase() ?>/FormParamController/process" method="post">
				
				<div class="label">First Name</div>
				<div class="inputField"><input type="text" name="name" style="margin-left: 75px;"/></div>

				<div class="label required">Email *</div>
				<div class="inputField"><input type="text" name="email" style="margin-left: 75px;"/></div>

				<div class="label">Comments</div>
				<div class="inputField"><textarea rows="10" cols="23" name="comments" style="margin-left: 75px;"></textarea></div>

				<div style="margin-left: 175px;"><input type="submit" value="Submit"/></div>
			</form>

		</div>

	</body>
</html>