<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<title><?= $title ?></title>
		<link href="<?= AgilePHP::getDocumentRoot() ?>/view/css/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>
		<?php require_once 'header.html'; ?>

		<div style="padding-bottom: 20px;">
			<a href="<?= AgilePHP::getRequestBase() ?>/LoginController">Login</a>
		</div>

		<?= $content ?>

		<?php require_once 'footer.html'; ?>
	</body>
</html>