<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<meta name="Description" content="This is the TestComponent home page"/>
		<title><?= $title ?></title>
		<link href="/view/css/style.css" type="text/css" rel="stylesheet"/>
	</head>

	<body>
		<div style="padding-top: 50px; padding-bottom: 50px; padding-left: 25px; text-align: left;">
			<?= $content ?>
		</div>		
	</body>
</html>
